spring:
  datasource:
    url: jdbc:mysql://47.116.98.38:3306/paper_push?serverTimezong=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liyihang123

  # 配置上传文件大小
  servlet:
    multipart:
      max-file-size: 500MB      # 最大文件限制
      max-request-size: 500MB   # 单次请求最大文件限制

# mybatis 信息
mybatis:
  # 加载 Mybatis 映射文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 配置 pojo 别名
  type-aliases-package: com.joush.entities
  # 配置下划线自动转驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
logging:
  level:
    com.nwu.mapper: debug

